openapi: 3.0.0
info:
  title: GRE Test Management API
  description: REST APIs for managing GRE tests, including questions for both Quantitative and Verbal sections with difficulty levels
  version: '1.0'

servers:
  - url: "http://localhost:3000"
    description: Local development environment

paths:
  /tests:
    get:
      operationId: get-tests
      summary: Retrieve a list of tests
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Test"
              example:
                - testID: 1
                  testName: "GRE Practice Test 1"
                  description: "A sample GRE practice test"
                  sections:
                    - section: "QUANT"
                      questions:
                        - questionID: 101
                          questionText: "What is 5 + 3?"
                          options: ["6", "7", "8", "9"]
                          correctOption: "8"
                          difficultyLevel: "EASY"
                        - questionID: 102
                          questionText: "If x + 3 = 7, what is x?"
                          options: ["1", "2", "3", "4"]
                          correctOption: "4"
                          difficultyLevel: "MEDIUM"
                        - questionID: 103
                          questionText: "Solve for x: 2x - 5 = 15"
                          options: ["8", "10", "12", "15"]
                          correctOption: "10"
                          difficultyLevel: "HARD"
                    - section: "VERBAL"
                      questions:
                        - questionID: 201
                          questionText: "Which of the following words is closest in meaning to 'happy'?"
                          options: ["Sad", "Joyful", "Angry", "Depressed"]
                          correctOption: "Joyful"
                          difficultyLevel: "EASY"
                        - questionID: 202
                          questionText: "Select the best antonym for 'difficult'."
                          options: ["Hard", "Easy", "Challenging", "Complex"]
                          correctOption: "Easy"
                          difficultyLevel: "MEDIUM"
                        - questionID: 203
                          questionText: "Which word most nearly means 'ephemeral'?"
                          options: ["Permanent", "Eternal", "Temporary", "Lasting"]
                          correctOption: "Temporary"
                          difficultyLevel: "HARD"
    post:
      operationId: create-test
      summary: Create a new test
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Test"
            example:
              testID: 2
              testName: "GRE Practice Test 2"
              description: "Another sample GRE practice test"
              sections:
                - section: "QUANT"
                  questions:
                    - questionID: 301
                      questionText: "What is 9 + 1?"
                      options: ["10", "11", "12", "9"]
                      correctOption: "10"
                      difficultyLevel: "EASY"
                    - questionID: 302
                      questionText: "If 2x = 14, what is x?"
                      options: ["5", "6", "7", "8"]
                      correctOption: "7"
                      difficultyLevel: "MEDIUM"
                    - questionID: 303
                      questionText: "Solve for y: 3y + 6 = 21"
                      options: ["3", "4", "5", "6"]
                      correctOption: "5"
                      difficultyLevel: "HARD"
                - section: "VERBAL"
                  questions:
                    - questionID: 401
                      questionText: "What is the opposite of 'hot'?"
                      options: ["Cold", "Warm", "Cool", "Lukewarm"]
                      correctOption: "Cold"
                      difficultyLevel: "EASY"
                    - questionID: 402
                      questionText: "Which word is the closest synonym for 'meticulous'?"
                      options: ["Careless", "Precise", "Lazy", "Rushed"]
                      correctOption: "Precise"
                      difficultyLevel: "MEDIUM"
                    - questionID: 403
                      questionText: "Which word most nearly means 'capricious'?"
                      options: ["Predictable", "Steady", "Unpredictable", "Consistent"]
                      correctOption: "Unpredictable"
                      difficultyLevel: "HARD"
      responses:
        '201':
          description: Test created successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /tests/{testID}:
    get:
      operationId: get-test
      summary: Retrieve a single test by ID
      parameters:
        - name: testID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Test"
              example:
                testID: 1
                testName: "GRE Practice Test 1"
                description: "A sample GRE practice test"
                sections:
                  - section: "QUANT"
                    questions:
                      - questionID: 101
                        questionText: "What is 5 + 3?"
                        options: ["6", "7", "8", "9"]
                        correctOption: "8"
                        difficultyLevel: "EASY"
                  - section: "VERBAL"
                    questions:
                      - questionID: 201
                        questionText: "Which of the following words is closest in meaning to 'happy'?"
                        options: ["Sad", "Joyful", "Angry", "Depressed"]
                        correctOption: "Joyful"
                        difficultyLevel: "EASY"
    put:
      operationId: update-test
      summary: Update an existing test
      parameters:
        - name: testID
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Test"
            example:
              testName: "Updated GRE Practice Test 1"
              description: "Updated description"
              sections:
                - section: "QUANT"
                  questions:
                    - questionID: 101
                      questionText: "Updated Quant Question"
                      options: ["1", "2", "3", "4"]
                      correctOption: "4"
                      difficultyLevel: "EASY"
      responses:
        '200':
          description: Test updated successfully
        '400':
          description: Bad request
        '404':
          description: Test not found
        '500':
          description: Server error

    delete:
      operationId: delete-test
      summary: Delete a test by ID
      parameters:
        - name: testID
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Test deleted successfully
        '404':
          description: Test not found
        '500':
          description: Server error

components:
  schemas:
    Test:
      type: object
      properties:
        testID:
          type: integer
        testName:
          type: string
        description:
          type: string
        sections:
          type: array
          items:
            type: object
            properties:
              section:
                type: string
              questions:
                type: array
                items:
                  type: object
                  properties:
                    questionID:
                      type: integer
                    questionText:
                      type: string
                    options:
                      type: array
                      items:
                        type: string
                    correctOption:
                      type: string
                    difficultyLevel:
                      type: string

    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
